### ISSUE TITLE
Make no longer works on Ubuntu 14.04.6

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#862]
From time to time I say `make OPT=-std=gnu99` on that machine. However, the last time it worked was

```
ulrich@p0:/opt/gupu/new-trealla$ ./tpl -v
Trealla Prolog (c) Infradig 2020, v2.79.13-3-gff01f
```
 From the next version on, I now get
```
/usr/bin/ld: src/bif_ffi.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [tpl] Error 1

**Comment by flexoron** [comment]
Makefile.
You can add it here again
```LDFLAGS += -lffi -ldl```

Sorry for it, __-ldl__ has been removed while BSD porting activity
(Background: contemporary Linux no longer need this lib, too)
